version: '3'
services:
  web:
    build: .
    restart: always
    command: npm start
    volumes:
      - ./src:/src
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb
      NODE_ENV: development
  mongodb:
    image: mongo
    restart: always
